[package]
name = "bearer"
version = "0.2.3"
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]
readme = "README.md"
keywords = ["OAuth2"]
categories = ["authentication", "command-line-interface"]
description = """Command line utility to generate HTTP Authorization header
 with bearer tokens. This is achieved with OAuth2 authorization code and
 refresh token workflow."""
license = "BSD-3-Clause"
documentation = "https://docs.rs/crate/bearer"
#homepage = "https://github.com/mardiros/bearer"
repository = "https://github.com/mardiros/bearer"

[dependencies]

libc = "^0.2.21"
clap = "^2.21.1"
log = "^0.3.7"
pretty_env_logger = "^0.1.0"
tilde-expand = "^0.1.1"
chrono = "^0.3.0"

toml = "^0.3.1"
serde = "^0.9.11"
serde_derive = "^0.9.11"
serde_json = "^0.9.9"

url = "^1.4.0"
cabot = "^0.1.3"

[dev-dependencies]
rand = "^0.3.15"
